name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow  }}-${{ github.event.pull_request.number || github.ref  }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Start etcd
        run: |
          docker run -p 2379:2379 -d -e ALLOW_NONE_AUTHENTICATION=yes --name etcd bitnami/etcd

      - name: Run Test
        run: go test --cover -v
