name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start etcd
        run: |
          docker run -p 2379:2379 -d -e ALLOW_NONE_AUTHENTICATION=yes --name etcd bitnami/etcd

      - name: Run Test
        run: go test --cover -v
